
# ??????
spring:
  application:
    name: museum

  # ?????
  datasource:
#    url: "jdbc:mysql://localhost:3306/tlias?useSSL=false&serverTimezone=UTC"
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis ???? spring ?????????
mybatis:
  # ????????
  configuration:
    map-underscore-to-camel-case: true
    # ??????? SQL??????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # ?? XML ??????????
  mapper-locations: classpath:mapper/*.xml
  # ???????? XML ?? resultType?
  type-aliases-package: com.iiyatsu.pojo

  #??????????
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug